@startuml

class Пользователь {
    - id: int
    - логин: str
    - ФИО: str
    - email: str
    - password: str
    + вход()
    + выход() 
     
}
class Студент {
    + записатьсяНаКурс()
    + посмотретьСертификат() 
    + посмотретьОценки()
     
}

class Преподаватель {
    + создатьКурс()
    + поставитьОценки() 
    + посмотретьАналитику()
}

class Курс {
    - id: int
    - название: str
    - описание: str
    - датаПубликации: date
    + добавитьМатериал()


}

class Оценка {
    - id: int
    - значение: str
    - датаПроставления: date
}

class Отзыв {
    - id: int
    - текстОтзыва: str
    - датаПубликации: date
}

class Сертификат {
  - id: int
  - датаВыдачи: date
}

Пользователь <|-- Студент
Пользователь <|-- Преподаватель


Студент "1" *-- "*" Оценка : получает
Курс "1" *-- "*" Отзыв
Студент "1" --> "*" Курс : записывается
Преподаватель "1" --> "*" Курс: создает
Курс "1" *-- "1" Сертификат
Преподаватель "1" --> "*" Оценка: ставит
@enduml