@startuml
actor Преподаватель

participant "Интерфейс" as UI
participant "Система" as api
database "Хранилище файлов" as Storage

Преподаватель -> UI: перенести видео и нажать кнопку "Загрузить"
UI -> api : передать файл 
activate api
api -> api: проверить формат 

alt корректный формат
    api -> Storage: сохранить во временную папку
    UI <- api: Файл загружен 

    Преподаватель -> UI: нажать "Сохранить"
    UI -> api: подтвердить сохраннение
    api -> Storage: переместить файл в хранилище
    UI <- api: Файл сохранен 

else некорректный формат
    UI <-api: ошибка "Некорректный формат"

end
@enduml