@startuml
!define RECTANGLE class

actor Пользователь
actor Студент
actor Преподаватель
actor "Незарегистрированный пользователь"
actor Техподдержка

Пользователь <|-- Студент
Пользователь <|-- Преподаватель
Пользователь <|-- "Незарегистрированный пользователь"

rectangle "Общие функции" {
    usecase "Просмотр курсов" as UC1
    usecase "Общение в чате" as UC4
    usecase "Просмотр отзывов" as UC9
}

rectangle "Функции для студента" {
    usecase "Изучение курса" as UC2
    usecase "Просмотр сертификатов" as UC5
    usecase "Просмотр оценок" as UC6
    usecase "Написание отзывов" as UC8
}

rectangle "Функции для преподавателя" {
    usecase "Создание курса" as UC3
    usecase "Проставление оценок" as UC7
    usecase "Просмотр аналитики" as UC10
}


Студент --> UC1
Студент --> UC2
Студент --> UC4
Студент --> UC5
Студент --> UC6
Студент --> UC8

Преподаватель --> UC1
Преподаватель --> UC3
Преподаватель --> UC4
Преподаватель --> UC6
Преподаватель --> UC7
Преподаватель --> UC9
Преподаватель --> UC10

"Незарегистрированный пользователь" --> UC1
Техподдержка --> UC1
Техподдержка --> UC9


UC8 ..> UC9 : <<extend>>

@enduml
